// yomp-contracts build — one authored source → generated TS + Kotlin outputs.
//
//   src/schemas/*.schema.json   --quicktype-->  build/ts + build/kotlin (shapes)
//   src/constants/community.json --codegen-->   build/ts + build/kotlin (constants)
//
// Kotlin is EMITTED only here; it is compiled later when yomp-android's :shared
// module consumes this repo as a submodule (mirrors how yomp-tokens works).
//
// Run: npm run build
import { execSync } from "node:child_process";
import { appendFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const KOTLIN_PACKAGE = "dog.yomp.contracts";

const TS_DIR = join(ROOT, "build", "ts");
const KT_DIR = join(ROOT, "build", "kotlin");
mkdirSync(TS_DIR, { recursive: true });
mkdirSync(KT_DIR, { recursive: true });

const SCHEMA = join(ROOT, "src", "schemas", "place-stats.schema.json");

// ── 1. Shapes via quicktype ────────────────────────────────────────────────
function quicktype(args) {
  execSync(`npx --yes quicktype ${args}`, { stdio: ["ignore", "pipe", "inherit"], cwd: ROOT });
}

const tsOut = join(TS_DIR, "place-stats.ts");
const ktOut = join(KT_DIR, "PlaceStats.kt");

quicktype(`--src-lang schema --lang ts --just-types --src "${SCHEMA}" -o "${tsOut}"`);
quicktype(`--src-lang schema --lang kotlin --framework just-types --package ${KOTLIN_PACKAGE} --src "${SCHEMA}" -o "${ktOut}"`);

// ── 2. Timestamp alias swap ─────────────────────────────────────────────────
// lastUpdated is a Firestore server Timestamp. quicktype emits an opaque object
// type from the schema's `$ref: Timestamp`; we replace that with the idiomatic
// per-platform alias (faithful to how the Firestore SDK deserialises it).
function aliasTimestampTs(file) {
  let s = readFileSync(file, "utf8");
  // Force the field REQUIRED (drop quicktype's `?`) and to the full write/read/null
  // union: Timestamp = reads, FieldValue = the serverTimestamp() write moment, null =
  // web's `?? null` / cleared. This is a TS-only narrowing — the shared schema keeps
  // lastUpdated optional (legacy docs) and Kotlin stays nullable `Timestamp?`.
  s = s.replace(/\blastUpdated\??\s*:\s*[^;\n]+/g, "lastUpdated: Timestamp | FieldValue | null");
  // Drop any generated `Timestamp` interface/type declaration.
  s = s.replace(/export interface Timestamp \{[\s\S]*?\n\}\n?/g, "");
  s = s.replace(/export type Timestamp = [^;]+;\n?/g, "");
  // Bind Timestamp + FieldValue to the real Firebase types via a type-only import
  // (parity with the Kotlin Timestamp alias; FieldValue has no Kotlin data-class form).
  s = `import type { FieldValue, Timestamp } from "firebase/firestore";\n\n${s}`;
  writeFileSync(file, s);
}

function aliasTimestampKotlin(file) {
  let s = readFileSync(file, "utf8");
  // Rewrite the whole lastUpdated type to `Timestamp?` (quicktype inlines the
  // opaque object as `Map<String, Any?>?`, whose embedded comma defeats a simple
  // token match — so match lazily to end-of-line, preserving any ` = null`/comma).
  s = s.replace(/(val lastUpdated:\s*).+?(\s*=\s*null)?(,)?(\r?\n)/g, "$1Timestamp?$2$3$4");
  // Drop any generated Timestamp class/typealias.
  s = s.replace(/(?:data )?class Timestamp \([\s\S]*?\)\n?/g, "");
  s = s.replace(/typealias Timestamp = .*\n?/g, "");
  // Inject the alias right after the package declaration.
  s = s.replace(
    /(package\s+[\w.]+\n)/,
    `$1\ntypealias Timestamp = com.google.firebase.Timestamp\n`,
  );
  writeFileSync(file, s);
}

// Narrow the TS attributeCounts map keys to AttributeKey (web parity). quicktype
// emits an open string-index signature from the schema's additionalProperties; rewrite
// it to Partial<Record<AttributeKey, AttributeCount>>. TS-only — Kotlin keeps
// Map<String, AttributeCount>? (no enum-keyed-map equivalent in the data class).
function narrowAttributeCountsTs(file) {
  let s = readFileSync(file, "utf8");
  s = s.replace(
    /(\battributeCounts\??\s*:\s*)\{\s*\[key:\s*string\]\s*:\s*AttributeCount\s*\}/g,
    "$1Partial<Record<AttributeKey, AttributeCount>>",
  );
  // Bind AttributeKey from the generated constants (sibling file in build/ts).
  s = `import type { AttributeKey } from "./constants";\n${s}`;
  writeFileSync(file, s);
}

aliasTimestampTs(tsOut);
narrowAttributeCountsTs(tsOut);
aliasTimestampKotlin(ktOut);

// ── 3. Constants codegen ────────────────────────────────────────────────────
const community = JSON.parse(readFileSync(join(ROOT, "src", "constants", "community.json"), "utf8"));
const { status, attributeKeys, thresholds, safeIdPattern } = community;

const tsList = (arr) => arr.map((v) => JSON.stringify(v)).join(", ");
const ktList = (arr) => arr.map((v) => JSON.stringify(v)).join(", ");

const tsConstants = `// AUTO-GENERATED by scripts/build.mjs from src/constants/community.json. Do not edit.

export const STATUS = [${tsList(status)}] as const;
export type Status = (typeof STATUS)[number];

export const ATTRIBUTE_KEYS = [${tsList(attributeKeys)}] as const;
export type AttributeKey = (typeof ATTRIBUTE_KEYS)[number];

export const MIN_COMMUNITY_VOTES = ${thresholds.MIN_COMMUNITY_VOTES};
export const HIGH_CONFIDENCE_VOTES = ${thresholds.HIGH_CONFIDENCE_VOTES};

/** Sanitises a raw placeId into a Firestore-safe doc id (matches the web app's safeId). */
export const SAFE_ID_PATTERN = /${safeIdPattern}/g;
export function safeId(id: string): string {
  return id.replace(SAFE_ID_PATTERN, "_");
}
`;
writeFileSync(join(TS_DIR, "constants.ts"), tsConstants);

const ktConstants = `// AUTO-GENERATED by scripts/build.mjs from src/constants/community.json. Do not edit.
package ${KOTLIN_PACKAGE}

object Community {
    val STATUS: List<String> = listOf(${ktList(status)})
    val ATTRIBUTE_KEYS: List<String> = listOf(${ktList(attributeKeys)})

    const val MIN_COMMUNITY_VOTES: Int = ${thresholds.MIN_COMMUNITY_VOTES}
    const val HIGH_CONFIDENCE_VOTES: Int = ${thresholds.HIGH_CONFIDENCE_VOTES}

    /** Sanitises a raw placeId into a Firestore-safe doc id (matches the web app's safeId). */
    val SAFE_ID_REGEX: Regex = Regex(${JSON.stringify(safeIdPattern)})

    fun safeId(id: String): String = id.replace(SAFE_ID_REGEX, "_")
}
`;
writeFileSync(join(KT_DIR, "Community.kt"), ktConstants);

// ── 4. Map constants codegen ────────────────────────────────────────────────
// Map/cluster constants live in their own source (src/constants/map.json) for clean
// separation from community.json. Emitted as STRUCTURED, typed contracts — a TS
// `as const` + interfaces, and Kotlin data classes — never a JSON blob. Literals are
// DERIVED by mapping over the source arrays, not hardcoded.
const map = JSON.parse(readFileSync(join(ROOT, "src", "constants", "map.json"), "utf8"));
const { mapCategoryKeys, clusterPolicy } = map;

const tsRadius = (r) => `{ minZoom: ${r.minZoom}, radius: ${r.radius} }`;
const tsBucket = (b) => `{ minCount: ${b.minCount}, outer: ${b.outer}, inner: ${b.inner}, font: ${b.font} }`;
const ktRadius = (r) => `ClusterRadiusRule(${r.minZoom}, ${r.radius})`;
const ktBucket = (b) => `ClusterCountBucket(${b.minCount}, ${b.outer}, ${b.inner}, ${b.font})`;

const tsMap = `
export const MAP_CATEGORY_KEYS = [${tsList(mapCategoryKeys)}] as const;
export type MapCategoryKey = (typeof MAP_CATEGORY_KEYS)[number];

export interface ClusterRadiusRule { minZoom: number; radius: number; }
export interface ClusterCountBucket { minCount: number; outer: number; inner: number; font: number; }
export interface ClusterPolicy {
  maxClusterRadiusByZoom: readonly ClusterRadiusRule[];
  countBuckets: readonly ClusterCountBucket[];
  spiderfyOnMaxZoom: boolean;
  clusterPerCategory: boolean;
}
export const CLUSTER_POLICY: ClusterPolicy = {
  maxClusterRadiusByZoom: [ ${clusterPolicy.maxClusterRadiusByZoom.map(tsRadius).join(", ")} ],
  countBuckets: [ ${clusterPolicy.countBuckets.map(tsBucket).join(", ")} ],
  spiderfyOnMaxZoom: ${clusterPolicy.spiderfyOnMaxZoom},
  clusterPerCategory: ${clusterPolicy.clusterPerCategory},
};
`;
appendFileSync(join(TS_DIR, "constants.ts"), tsMap);

const ktMap = `// AUTO-GENERATED by scripts/build.mjs from src/constants/map.json. Do not edit.
package ${KOTLIN_PACKAGE}

val MAP_CATEGORY_KEYS: List<String> = listOf(${ktList(mapCategoryKeys)})

data class ClusterRadiusRule(val minZoom: Int, val radius: Int)
data class ClusterCountBucket(val minCount: Int, val outer: Int, val inner: Int, val font: Int)
data class ClusterPolicy(
    val maxClusterRadiusByZoom: List<ClusterRadiusRule>,
    val countBuckets: List<ClusterCountBucket>,
    val spiderfyOnMaxZoom: Boolean,
    val clusterPerCategory: Boolean,
)

val CLUSTER_POLICY: ClusterPolicy = ClusterPolicy(
    maxClusterRadiusByZoom = listOf(${clusterPolicy.maxClusterRadiusByZoom.map(ktRadius).join(", ")}),
    countBuckets = listOf(${clusterPolicy.countBuckets.map(ktBucket).join(", ")}),
    spiderfyOnMaxZoom = ${clusterPolicy.spiderfyOnMaxZoom},
    clusterPerCategory = ${clusterPolicy.clusterPerCategory},
)
`;
writeFileSync(join(KT_DIR, "Map.kt"), ktMap);

console.log("✔ build complete — build/ts + build/kotlin");
